server:
  port: 8000
  servlet:
    context-path: /v1/api
spring:
  datasource:
    url: jdbc:h2:file:~/prova-leroy.h2
    driverClassName: org.h2.Driver
    username: sa
    password: p455w0rd
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

storage:
  directory: /tmp/upload